# Generated by Django 5.0.6 on 2024-10-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ser_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
