# Generated by Django 5.0.6 on 2024-10-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0004_profile_ser_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ser_name',
            new_name='surname',
        ),
    ]
