# Generated by Django 5.0.6 on 2024-06-18 05:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('temperature_info', models.IntegerField(default=0)),
                ('data_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Station',
            },
        ),
        migrations.CreateModel(
            name='Arduino',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('temperature_info', models.IntegerField(default=0)),
                ('update_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arduinoapp.station')),
            ],
            options={
                'verbose_name': 'Arduino',
            },
        ),
    ]
