# Generated by Django 5.0.6 on 2024-10-18 10:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduinoapp', '0004_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microcomputer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('temperature_info', models.IntegerField(default=0)),
                ('update_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arduinoapp.station')),
            ],
            options={
                'verbose_name': 'Microcomputer',
            },
        ),
    ]
