# Generated by Django 5.0.6 on 2024-10-08 09:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('temperature_info', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('temperature_info', models.CharField(max_length=100)),
                ('data_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Stations',
            },
        ),
        migrations.CreateModel(
            name='Microcomputer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('temperature_info', models.IntegerField(default=0)),
                ('update_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rcs_2.station')),
            ],
            options={
                'verbose_name': 'Microcomputer',
            },
        ),
        migrations.CreateModel(
            name='Arduino',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('temperature_info', models.IntegerField(default=0)),
                ('update_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rcs_2.station')),
            ],
            options={
                'verbose_name': 'Arduino',
            },
        ),
    ]
